name = "bigdecimal"
version = "0.1.0"

description = "Arbitrary precision decimal arithmetic for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "horvathandris", repo = "bigdecimal" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
bigi = ">= 3.2.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript.deno]
allow_read = ["gleam.toml", "test", "build"]
